In [11]:
import numpy as np

In [77]:
arr = np.array([23,45,67,23])
print(type(arr ))

<class 'numpy.ndarray'>


In [14]:
lst = [45,34,67,90,23]
arr=np.array(lst)
print(type(arr))


<class 'numpy.ndarray'>


In [17]:
mat = ((2,3,4),
       (4,5,6),
       (7,8,9))

matrix = np.array(mat)
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.nbytes)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
72


In [18]:
matrix.T

array([[2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

In [19]:
list(matrix.flat)

[np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
print(np.ones(3))
print(np.ones((2,3,4)))

[1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [42]:
np.empty((3))

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [48]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [61]:
np.arange(1,10)
np.arange(1,10).reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [64]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [65]:
np.sort(arr)

array([23, 34, 45, 67, 90])

In [66]:
np.sort(arr,kind='stable')    

array([23, 34, 45, 67, 90])

np.sort(data.order='name')
for sorting data

In [67]:
arrl= np.array([23,45,67,23])
arr2 = np.array([45,34,67,90,23])
np.concatenate((arrl,arr2))


array([23, 45, 67, 23, 45, 34, 67, 90, 23])

In [69]:
arr1 = np.array([[32,23],
                [45,67]])
arr2 = np.array([[45,34],    
                [67,90]])
np.concatenate((arr1,arr2),axis=0)
                              
               

array([[32, 23],
       [45, 67],
       [45, 34],
       [67, 90]])

In [78]:
a2 = arr[:,np.newaxis]
print(a2.shape)

(4, 1)


In [80]:
a2 = arr[:,np.newaxis]
print(a2)

[[23]
 [45]
 [67]
 [23]]


In [81]:
print(arr)
a2 = arr[np.newaxis,:]
print(a2)

[23 45 67 23]
[[23 45 67 23]]


In [82]:
a2 = arr[np.newaxis,:]
print(a2.shape)

(1, 4)
